// pages/login.vue
<script setup lang="ts">
import Card from '~/components/ui/Card.vue'
import Input from '~/components/ui/Input.vue'
import Button from '~/components/ui/Button.vue'
import Label from '~/components/ui/Label.vue'

definePageMeta({ middleware: 'guest' })

const authStore = useAuthStore()
const route = useRoute()

const form = reactive({
  username: '',
  password: '',
})
const submitting = ref(false)
const error = ref('')

const nextPath = computed(() => String(route.query.redirect || '/admin/assets/inventory'))

async function handleSubmit() {
  submitting.value = true
  error.value = ''
  try {
    await authStore.login({
      username: form.username.trim(),
      password: form.password,
    })
    await navigateTo(nextPath.value, { replace: true })
  } catch (submitError) {
    error.value = submitError instanceof Error ? submitError.message : 'Login failed'
  } finally {
    submitting.value = false
  }
}
</script>

<template>
  <div class="flex min-h-screen items-center justify-center bg-slate-100 px-4 py-8">
    <Card class="w-full max-w-md">
      <div class="p-8">
        <div class="mb-6 flex items-center gap-3">
          <div class="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-600 text-sm font-semibold text-white">
            FL
          </div>
          <div>
            <p class="text-base font-semibold text-slate-900">Frostlink</p>
            <p class="text-xs text-slate-500">Operations Platform</p>
          </div>
        </div>
        <h1 class="text-2xl font-semibold text-slate-900">Welcome back</h1>
        <p class="mt-2 text-sm text-slate-600">Sign in to access the operations dashboard.</p>

        <form class="mt-6 space-y-4" @submit.prevent="handleSubmit">
          <div class="space-y-2">
            <Label for="username">Email</Label>
            <Input id="username" v-model="form.username" type="email" autocomplete="email" required />
          </div>
          <div class="space-y-2">
            <Label for="password">Password</Label>
            <Input id="password" v-model="form.password" type="password" autocomplete="current-password" required />
          </div>
          <p v-if="error" class="text-sm text-red-600">{{ error }}</p>
          <Button type="submit" class="w-full" :disabled="submitting">
            {{ submitting ? 'Signing in...' : 'Sign in' }}
          </Button>
          <p class="text-center text-sm text-slate-600">
            Need an account?
            <NuxtLink to="/signup" class="font-medium text-blue-600 hover:underline">Create one</NuxtLink>
          </p>
        </form>
      </div>
    </Card>
  </div>
</template>

// src/app/pages/login.tsx
import { FormEvent, useMemo, useState } from "react";
import { useLocation, useNavigate } from "react-router";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../components/ui/card";
import { Input } from "../components/ui/input";
import { Button } from "../components/ui/button";
import { Label } from "../components/ui/label";
import { useAuth } from "../auth/auth-context";

export function LoginPage() {
  const { login } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();

  const nextPath = useMemo(() => {
    const state = location.state as { from?: { pathname?: string } } | null;
    return state?.from?.pathname || "/admin/assets";
  }, [location.state]);

  const [form, setForm] = useState({ username: "", password: "" });
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState("");

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setSubmitting(true);
    setError("");

    try {
      await login({ username: form.username.trim(), password: form.password });
      navigate(nextPath, { replace: true });
    } catch (submitError) {
      const message = submitError instanceof Error ? submitError.message : "Login failed";
      setError(message);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-100 flex items-center justify-center px-4 py-8">
      <Card className="w-full max-w-md">
        <CardHeader>
          <div className="flex items-center gap-3 mb-3">
            <div className="h-10 w-10 rounded-lg bg-blue-600 text-white flex items-center justify-center font-semibold">
              FL
            </div>
            <div>
              <p className="text-base font-semibold text-gray-900 leading-none">Frostlink</p>
              <p className="text-xs text-gray-600 mt-1">Application Platform</p>
            </div>
          </div>
          <CardTitle>Welcome back</CardTitle>
          <CardDescription>Sign in to access Frostlink.</CardDescription>
        </CardHeader>
        <CardContent>
          <form className="space-y-4" onSubmit={handleSubmit}>
            <div className="space-y-2">
              <Label htmlFor="username">Email</Label>
              <Input
                id="username"
                type="email"
                autoComplete="email"
                value={form.username}
                onChange={(event) => setForm((prev) => ({ ...prev, username: event.target.value }))}
                required
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="password">Password</Label>
              <Input
                id="password"
                type="password"
                autoComplete="current-password"
                value={form.password}
                onChange={(event) => setForm((prev) => ({ ...prev, password: event.target.value }))}
                required
              />
            </div>

            {error ? <p className="text-sm text-red-600">{error}</p> : null}

            <Button type="submit" className="w-full" disabled={submitting}>
              {submitting ? "Signing in..." : "Sign in"}
            </Button>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}
