// pages/settings.vue
<script setup lang="ts">
import { Settings as SettingsIcon, User } from "lucide-vue-next";
import Card from "~/components/ui/Card.vue";
import Button from "~/components/ui/Button.vue";
import Input from "~/components/ui/Input.vue";
import Label from "~/components/ui/Label.vue";
import OrganisationAssetValidationSettingsCard from "~/components/settings/OrganisationAssetValidationSettingsCard.vue";
import { hasPermission } from "~/utils/permissionPolicy";

definePageMeta({ layout: "dashboard", middleware: "auth" });

type ProfileDetails = {
  id: number;
  username: string;
  full_name: string | null;
  first_name: string | null;
  last_name: string | null;
  permissions: string;
  organisation_id: number | null;
  organisation_name: string | null;
  organisation_domin: string | null;
};

const { request } = useApiClient();
const authStore = useAuthStore();
const canViewTotalUnits = computed(() =>
  authStore.session?.user.permissions
    ? hasPermission(authStore.session.user.permissions, "assets.view")
    : false,
);

const profile = ref<ProfileDetails | null>(null);
const profileLoading = ref(false);
const profileError = ref("");
const profileSaving = ref(false);
const profileSaveError = ref("");
const profileSaveSuccess = ref("");
const passwordSaving = ref(false);
const passwordError = ref("");
const passwordSuccess = ref("");

const profileForm = reactive({
  first_name: "",
  last_name: "",
  username: "",
});

const passwordForm = reactive({
  new_password: "",
  confirm_password: "",
});

async function loadProfile() {
  profileLoading.value = true;
  profileError.value = "";
  try {
    const data = await request<ProfileDetails>("/profile");
    profile.value = data;
    profileForm.first_name = data.first_name || "";
    profileForm.last_name = data.last_name || "";
    profileForm.username = data.username || "";
  } catch (error) {
    profileError.value =
      error instanceof Error
        ? error.message
        : "Could not load profile details.";
  } finally {
    profileLoading.value = false;
  }
}

async function submitProfileUpdate() {
  profileSaving.value = true;
  profileSaveError.value = "";
  profileSaveSuccess.value = "";
  try {
    const updatedProfile = await request<ProfileDetails>("/profile", {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        username: profileForm.username.trim(),
        first_name: profileForm.first_name.trim(),
        last_name: profileForm.last_name.trim(),
      }),
    });
    profile.value = updatedProfile;
    profileSaveSuccess.value = "Profile updated.";
    if (authStore.session) {
      authStore.setSession({
        ...authStore.session,
        user: {
          ...authStore.session.user,
          username: updatedProfile.username,
          full_name: updatedProfile.full_name,
        },
      });
    }
  } catch (error) {
    profileSaveError.value =
      error instanceof Error
        ? error.message
        : "Could not update profile details.";
  } finally {
    profileSaving.value = false;
  }
}

async function submitPasswordChange() {
  const userId = authStore.session?.user.id;
  if (!userId) {
    passwordError.value = "Could not resolve current user.";
    return;
  }
  if (passwordForm.new_password.length < 8) {
    passwordError.value = "Password must be at least 8 characters.";
    return;
  }
  if (passwordForm.new_password !== passwordForm.confirm_password) {
    passwordError.value = "Passwords do not match.";
    return;
  }
  passwordSaving.value = true;
  passwordError.value = "";
  passwordSuccess.value = "";
  try {
    await request(`/users/${userId}/password`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ new_password: passwordForm.new_password }),
    });
    passwordForm.new_password = "";
    passwordForm.confirm_password = "";
    passwordSuccess.value = "Password updated.";
  } catch (error) {
    passwordError.value =
      error instanceof Error ? error.message : "Could not update password.";
  } finally {
    passwordSaving.value = false;
  }
}

onMounted(() => {
  void loadProfile();
});
</script>

<template>
  <div class="mx-auto max-w-[1440px] space-y-6 p-4 md:p-6 lg:p-8">
    <div>
      <div class="flex items-center gap-3">
        <SettingsIcon class="h-6 w-6 text-[#006aea]" />
        <h1 class="text-2xl font-semibold text-slate-900">Settings</h1>
      </div>
      <p class="mt-1 pl-9 text-sm text-slate-600">
        Profile, security, and data validation configuration.
      </p>
    </div>

    <div class="grid gap-6 lg:grid-cols-[2.2fr_0.8fr]">
      <div class="space-y-6">
        <Card>
          <div class="border-b border-slate-200 p-5">
            <div class="flex items-center gap-2">
              <User class="h-4 w-4 text-[#006aea]" />
              <h2 class="text-lg font-semibold text-slate-900">
                Profile Settings
              </h2>
            </div>
          </div>
          <div class="space-y-4 p-5">
            <p v-if="profileError" class="text-sm text-red-600">
              {{ profileError }}
            </p>
            <p v-if="profileSaveError" class="text-sm text-red-600">
              {{ profileSaveError }}
            </p>
            <p v-if="profileSaveSuccess" class="text-sm text-emerald-600">
              {{ profileSaveSuccess }}
            </p>

            <div class="grid gap-4 md:grid-cols-2">
              <div class="space-y-1">
                <Label for="first-name">First Name</Label>
                <Input id="first-name" v-model="profileForm.first_name" />
              </div>
              <div class="space-y-1">
                <Label for="last-name">Last Name</Label>
                <Input id="last-name" v-model="profileForm.last_name" />
              </div>
            </div>
            <div class="space-y-1">
              <Label for="email">Email</Label>
              <Input id="email" v-model="profileForm.username" type="email" />
            </div>
            <div class="grid gap-4 md:grid-cols-2">
              <div class="space-y-1">
                <Label for="role">Role</Label>
                <Input
                  id="role"
                  :model-value="profile?.permissions || ''"
                  readonly
                />
              </div>
              <div class="space-y-1">
                <Label for="organisation">Organisation</Label>
                <Input
                  id="organisation"
                  :model-value="profile?.organisation_name || ''"
                  readonly
                />
              </div>
            </div>
            <div class="flex gap-2">
              <Button
                :disabled="profileSaving || profileLoading"
                @click="submitProfileUpdate"
                >{{ profileSaving ? "Saving..." : "Save Profile" }}</Button
              >
              <Button
                variant="outline"
                :disabled="profileSaving || profileLoading"
                @click="loadProfile"
                >{{
                  profileLoading ? "Refreshing..." : "Refresh Profile"
                }}</Button
              >
            </div>

            <div class="border-t border-slate-200 pt-4">
              <h3 class="text-sm font-semibold text-slate-900">
                Change Password
              </h3>
              <div class="mt-3 space-y-3">
                <div class="space-y-1">
                  <Label for="new-password">New Password</Label>
                  <Input
                    id="new-password"
                    v-model="passwordForm.new_password"
                    type="password"
                  />
                </div>
                <div class="space-y-1">
                  <Label for="confirm-password">Confirm New Password</Label>
                  <Input
                    id="confirm-password"
                    v-model="passwordForm.confirm_password"
                    type="password"
                  />
                </div>
                <p v-if="passwordError" class="text-sm text-red-600">
                  {{ passwordError }}
                </p>
                <p v-if="passwordSuccess" class="text-sm text-emerald-600">
                  {{ passwordSuccess }}
                </p>
                <Button
                  :disabled="passwordSaving"
                  @click="submitPasswordChange"
                  >{{
                    passwordSaving ? "Updating..." : "Update Password"
                  }}</Button
                >
              </div>
            </div>
          </div>
        </Card>

        <OrganisationAssetValidationSettingsCard />
      </div>

      <Card>
        <div class="border-b border-slate-200 p-5">
          <div class="flex items-center gap-2">
            <SettingsIcon class="h-4 w-4 text-[#006aea]" />
            <h2 class="text-lg font-semibold text-slate-900">System Info</h2>
          </div>
        </div>
        <div class="space-y-4 p-5 text-sm">
          <div>
            <p class="text-slate-500">Version</p>
            <p class="font-medium text-slate-900">Frostlink v1.2.4</p>
          </div>
          <div>
            <p class="text-slate-500">Last Data Sync</p>
            <p class="font-medium text-slate-900">2 minutes ago</p>
          </div>
          <div v-if="canViewTotalUnits">
            <p class="text-slate-500">Total Units</p>
            <p class="font-medium text-slate-900">624 active</p>
          </div>
          <div>
            <p class="text-slate-500">Data Retention</p>
            <p class="font-medium text-slate-900">90 days</p>
          </div>
        </div>
      </Card>
    </div>
  </div>
</template>

// src/app/pages/settings.tsx
import { FormEvent, useEffect, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card";
import { Settings as SettingsIcon, User, Database } from "lucide-react";
import { Button } from "../components/ui/button";
import { Input } from "../components/ui/input";
import { Label } from "../components/ui/label";
import { Separator } from "../components/ui/separator";
import { OrganisationAssetValidationSettingsCard } from "../components/settings/organisation-asset-validation-settings-card";
import { useApiClient } from "../auth/use-api-client";
import { useAuth } from "../auth/auth-context";

type ProfileDetails = {
  id: number;
  username: string;
  full_name: string | null;
  first_name: string | null;
  last_name: string | null;
  permissions: string;
  organisation_id: number | null;
  organisation_name: string | null;
  organisation_domin: string | null;
};

export function SettingsPage() {
  const { request } = useApiClient();
  const { session, setSession } = useAuth();
  const canViewTotalUnits = session?.user.permissions === "Admin" || session?.user.permissions === "Fleet Manager";
  const [profile, setProfile] = useState<ProfileDetails | null>(null);
  const [profileLoading, setProfileLoading] = useState(false);
  const [profileError, setProfileError] = useState("");
  const [profileSaving, setProfileSaving] = useState(false);
  const [profileSaveError, setProfileSaveError] = useState("");
  const [profileSaveSuccess, setProfileSaveSuccess] = useState("");
  const [passwordForm, setPasswordForm] = useState({
    new_password: "",
    confirm_password: "",
  });
  const [passwordSaving, setPasswordSaving] = useState(false);
  const [passwordError, setPasswordError] = useState("");
  const [passwordSuccess, setPasswordSuccess] = useState("");
  const [profileForm, setProfileForm] = useState({
    first_name: "",
    last_name: "",
    username: "",
  });

  const loadProfile = async () => {
    setProfileLoading(true);
    setProfileError("");
    try {
      const data = await request<ProfileDetails>("/profile");
      setProfile(data);
      setProfileForm({
        first_name: data.first_name || "",
        last_name: data.last_name || "",
        username: data.username || "",
      });
      setProfileSaveError("");
      setProfileSaveSuccess("");
    } catch (error) {
      const message = error instanceof Error ? error.message : "Could not load profile details.";
      setProfileError(message);
    } finally {
      setProfileLoading(false);
    }
  };

  useEffect(() => {
    void loadProfile();
    // request comes from hook context and is stable enough for initial load.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const submitProfileUpdate = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setProfileSaveError("");
    setProfileSaveSuccess("");
    setProfileSaving(true);

    try {
      const updatedProfile = await request<ProfileDetails>("/profile", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          username: profileForm.username.trim(),
          first_name: profileForm.first_name.trim(),
          last_name: profileForm.last_name.trim(),
        }),
      });

      setProfile(updatedProfile);
      setProfileForm({
        first_name: updatedProfile.first_name || "",
        last_name: updatedProfile.last_name || "",
        username: updatedProfile.username || "",
      });
      setProfileSaveSuccess("Profile updated.");

      if (session) {
        setSession({
          ...session,
          user: {
            ...session.user,
            username: updatedProfile.username,
            full_name: updatedProfile.full_name,
          },
        });
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : "Could not update profile details.";
      setProfileSaveError(message);
    } finally {
      setProfileSaving(false);
    }
  };

  const submitPasswordChange = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setPasswordError("");
    setPasswordSuccess("");

    const userId = session?.user.id;
    if (!userId) {
      setPasswordError("Could not resolve current user.");
      return;
    }

    const newPassword = passwordForm.new_password;
    const confirmPassword = passwordForm.confirm_password;

    if (newPassword.length < 8) {
      setPasswordError("Password must be at least 8 characters.");
      return;
    }
    if (newPassword !== confirmPassword) {
      setPasswordError("Passwords do not match.");
      return;
    }

    setPasswordSaving(true);
    try {
      await request(`/users/${userId}/password`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ new_password: newPassword }),
      });
      setPasswordForm({ new_password: "", confirm_password: "" });
      setPasswordSuccess("Password updated.");
    } catch (error) {
      const message = error instanceof Error ? error.message : "Could not update password.";
      setPasswordError(message);
    } finally {
      setPasswordSaving(false);
    }
  };

  return (
    <div className="p-8 max-w-[1440px] mx-auto">
      <h1 className="text-3xl font-semibold text-gray-900 flex items-center gap-2 mb-6">
        <SettingsIcon className="w-8 h-8 text-blue-600" />
        Settings
      </h1>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Main Settings */}
        <div className="lg:col-span-2 space-y-6">
          {/* Profile Settings */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <User className="w-5 h-5" />
                Profile Settings
              </CardTitle>
            </CardHeader>
            <CardContent>
              {profileError ? <p className="text-sm text-red-600">{profileError}</p> : null}
              <form onSubmit={(event) => void submitProfileUpdate(event)} className="space-y-4">
                {profileSaveError ? <p className="text-sm text-red-600">{profileSaveError}</p> : null}
                {profileSaveSuccess ? <p className="text-sm text-green-600">{profileSaveSuccess}</p> : null}

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label htmlFor="first-name">First Name</Label>
                    <Input
                      id="first-name"
                      value={profileForm.first_name}
                      className="mt-1.5"
                      disabled={profileLoading || profileSaving}
                      onChange={(event) => {
                        setProfileSaveSuccess("");
                        setProfileForm((prev) => ({ ...prev, first_name: event.target.value }));
                      }}
                    />
                  </div>
                  <div>
                    <Label htmlFor="last-name">Last Name</Label>
                    <Input
                      id="last-name"
                      value={profileForm.last_name}
                      className="mt-1.5"
                      disabled={profileLoading || profileSaving}
                      onChange={(event) => {
                        setProfileSaveSuccess("");
                        setProfileForm((prev) => ({ ...prev, last_name: event.target.value }));
                      }}
                    />
                  </div>
                </div>
                <div>
                  <Label htmlFor="email">Email</Label>
                  <Input
                    id="email"
                    type="email"
                    value={profileForm.username}
                    className="mt-1.5"
                    disabled={profileLoading || profileSaving}
                    onChange={(event) => {
                      setProfileSaveSuccess("");
                      setProfileForm((prev) => ({ ...prev, username: event.target.value }));
                    }}
                    required
                  />
                </div>
                <div>
                  <Label htmlFor="role">Role</Label>
                  <Input
                    id="role"
                    value={profile?.permissions || ""}
                    className="mt-1.5"
                    readOnly
                    disabled={profileLoading || profileSaving}
                  />
                </div>
                <div>
                  <Label htmlFor="organisation">Organisation</Label>
                  <Input
                    id="organisation"
                    value={profile?.organisation_name || ""}
                    className="mt-1.5"
                    readOnly
                    disabled={profileLoading || profileSaving}
                  />
                </div>
                <div>
                  <Label htmlFor="organisation-domain">Organisation Domain</Label>
                  <Input
                    id="organisation-domain"
                    value={profile?.organisation_domin || ""}
                    className="mt-1.5"
                    readOnly
                    disabled={profileLoading || profileSaving}
                  />
                </div>
                <div className="flex gap-2">
                  <Button type="submit" disabled={profileLoading || profileSaving}>
                    {profileSaving ? "Saving..." : "Save Profile"}
                  </Button>
                  <Button
                    type="button"
                    variant="outline"
                    onClick={() => void loadProfile()}
                    disabled={profileLoading || profileSaving}
                  >
                    {profileLoading ? "Refreshing..." : "Refresh Profile"}
                  </Button>
                </div>
              </form>

              <Separator className="my-6" />

              <form onSubmit={(event) => void submitPasswordChange(event)} className="space-y-4">
                <h3 className="text-sm font-medium">Change Password</h3>
                {passwordError ? <p className="text-sm text-red-600">{passwordError}</p> : null}
                {passwordSuccess ? <p className="text-sm text-green-600">{passwordSuccess}</p> : null}
                <div>
                  <Label htmlFor="new-password">New Password</Label>
                  <Input
                    id="new-password"
                    type="password"
                    value={passwordForm.new_password}
                    className="mt-1.5"
                    disabled={passwordSaving || profileLoading}
                    onChange={(event) => {
                      setPasswordSuccess("");
                      setPasswordForm((prev) => ({ ...prev, new_password: event.target.value }));
                    }}
                  />
                </div>
                <div>
                  <Label htmlFor="confirm-password">Confirm New Password</Label>
                  <Input
                    id="confirm-password"
                    type="password"
                    value={passwordForm.confirm_password}
                    className="mt-1.5"
                    disabled={passwordSaving || profileLoading}
                    onChange={(event) => {
                      setPasswordSuccess("");
                      setPasswordForm((prev) => ({ ...prev, confirm_password: event.target.value }));
                    }}
                  />
                </div>
                <Button type="submit" disabled={passwordSaving || profileLoading}>
                  {passwordSaving ? "Updating..." : "Update Password"}
                </Button>
              </form>
            </CardContent>
          </Card>

          <OrganisationAssetValidationSettingsCard />

        </div>

        {/* Side Panel */}
        <div className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Database className="w-5 h-5" />
                System Info
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              <div>
                <p className="text-sm text-gray-600">Version</p>
                <p className="font-medium">Frostlink v1.2.4</p>
              </div>
              <Separator />
              <div>
                <p className="text-sm text-gray-600">Last Data Sync</p>
                <p className="font-medium">2 minutes ago</p>
              </div>
              {canViewTotalUnits ? (
                <>
                  <Separator />
                  <div>
                    <p className="text-sm text-gray-600">Total Units</p>
                    <p className="font-medium">624 active</p>
                  </div>
                </>
              ) : null}
              <Separator />
              <div>
                <p className="text-sm text-gray-600">Data Retention</p>
                <p className="font-medium">90 days</p>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
