// src/app/components/dashboard/status-badge.tsx
import { Badge } from "../ui/badge";
import { cn } from "../ui/utils";

export type StatusType = "ok" | "warn" | "bad" | "med" | "high";

interface StatusBadgeProps {
  status: StatusType;
  label: string;
  className?: string;
}

export function StatusBadge({ status, label, className }: StatusBadgeProps) {
  const config = {
    ok: "bg-green-100 text-green-800 border-green-300",
    warn: "bg-yellow-100 text-yellow-800 border-yellow-300",
    bad: "bg-red-100 text-red-800 border-red-300",
    med: "bg-orange-100 text-orange-800 border-orange-300",
    high: "bg-red-100 text-red-800 border-red-300",
  };

  return (
    <Badge
      variant="outline"
      className={cn("font-medium text-xs", config[status], className)}
    >
      {label}
    </Badge>
  );
}

// apps/frontend/components/dashboard/StatusBadge.vue
<script setup lang="ts">
import Badge from '~/components/ui/Badge.vue'

defineProps<{
  status: 'ok' | 'med' | 'high' | 'warn' | 'bad' | 'no-data'
  label?: string
}>()
</script>

<template>
  <Badge
    :class="{
      'bg-emerald-100 text-emerald-700': status === 'ok',
      'bg-amber-100 text-amber-700': status === 'med' || status === 'warn',
      'bg-red-100 text-red-700': status === 'high' || status === 'bad',
      'bg-slate-100 text-slate-500': status === 'no-data',
    }"
  >
    {{ label || status }}
  </Badge>
</template>
