// src/app/components/dashboard/tier-badge.tsx
import { Badge } from "../ui/badge";
import { cn } from "../ui/utils";

export type TierType = "gold" | "silver" | "bronze" | "insufficient";

interface TierBadgeProps {
  tier: TierType;
  className?: string;
}

export function TierBadge({ tier, className }: TierBadgeProps) {
  const config = {
    gold: {
      label: "Gold",
      className: "bg-yellow-100 text-yellow-800 border-yellow-300",
    },
    silver: {
      label: "Silver",
      className: "bg-gray-100 text-gray-800 border-gray-300",
    },
    bronze: {
      label: "Bronze",
      className: "bg-orange-100 text-orange-800 border-orange-300",
    },
    insufficient: {
      label: "Insufficient Data",
      className: "bg-gray-50 text-gray-600 border-gray-200",
    },
  };

  const { label, className: tierClassName } = config[tier];

  return (
    <Badge
      variant="outline"
      className={cn("font-medium", tierClassName, className)}
    >
      {label}
    </Badge>
  );
}

// apps/frontend/components/dashboard/TierBadge.vue
<script setup lang="ts">
import Badge from '~/components/ui/Badge.vue'

defineProps<{
  tier: 'gold' | 'silver' | 'bronze' | 'insufficient'
}>()
</script>

<template>
  <Badge
    :class="{
      'bg-amber-100 text-amber-800': tier === 'gold',
      'bg-slate-200 text-slate-700': tier === 'silver',
      'bg-orange-100 text-orange-700': tier === 'bronze',
      'bg-slate-100 text-slate-500': tier === 'insufficient',
    }"
  >
    {{ tier }}
  </Badge>
</template>
